# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Isn't this blog beautiful?
tagline:          Visit me at https://github.com/kaysabelle/
paginate:         1
url:			        kaysabelle.github.io
baseurl:          /blog/
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
encoding: utf-8
